services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mailhog
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/users_db2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - APP_BASE_URL=http://localhost:8080
      # ДОБАВЬ ЭТИ НАСТРОЙКИ ПОЧТЫ:
      - SPRING_MAIL_HOST=mailhog
      - SPRING_MAIL_PORT=1025
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=false
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=false
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE=false
    volumes:
      - uploads_data:/app/uploads
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=users_db2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"   # SMTP порт
      - "8025:8025"   # Web UI для просмотра писем
    restart: unless-stopped

volumes:
  postgres_data:
  uploads_data: